//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegExSplitter.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string btnConvert_Text {
            get {
                return ResourceManager.GetString("btnConvert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split a single-line JavaScript Regular Expression into multiple lines of code..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx Splitter - Ryadel.IO.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx Multi-Line Splitter.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;code&gt;new RegExp([regexp], [modifiers])&lt;/code&gt; JavaScript code snippet containing the given RegEx escaped &amp; splitted into multiple lines..
        /// </summary>
        public static string txtMulti_Help {
            get {
                return ResourceManager.GetString("txtMulti_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Line JS code.
        /// </summary>
        public static string txtMulti_Label {
            get {
                return ResourceManager.GetString("txtMulti_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...your result will be shown here..
        /// </summary>
        public static string txtMulti_Placeholder {
            get {
                return ResourceManager.GetString("txtMulti_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of chars for each line:.
        /// </summary>
        public static string txtNumChars_Text {
            get {
                return ResourceManager.GetString("txtNumChars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid input examples: &lt;code&gt;/your-regex/g&lt;/code&gt; or &lt;code&gt;var re = /your-regex/g&lt;/code&gt; or &lt;code&gt;var re = new RegExp(&quot;your-regex&quot;, &quot;g&quot;)&lt;/code&gt; and so on..
        /// </summary>
        public static string txtSingle_Help {
            get {
                return ResourceManager.GetString("txtSingle_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a single-line JS RegExp.
        /// </summary>
        public static string txtSingle_Label {
            get {
                return ResourceManager.GetString("txtSingle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put your code here....
        /// </summary>
        public static string txtSingle_Placeholder {
            get {
                return ResourceManager.GetString("txtSingle_Placeholder", resourceCulture);
            }
        }
    }
}
